"use strict";
try {
    let x = 10;
	console.log("Continuamos...")
    miFuncion()
} catch (error){
	console.log("Error")
    console.log(error)
}
finally {
    console.log("Finalmente")
    console.log("Termina la revisi√≥n de errores")
}

console.log("Fin del programa")
